### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by mml1** [nellymull/prj-rev-bwfs-dasmoto#6]
(Meets Expectations) Great job! I liked your use of the '*' tag to target all the text to change the font-family. In addition, your code is well formatted and readable but be sure to keep the formatting consistent. The area of improvement here is to use 'id' tags to target unique changes and 'class' tags to prevent you from repeating code.

Overall, great work! I would suggest making the changes so that you are using the DRY principle to future solidify what you have learned here.

**Comment by nellymull** [comment]
Thank you! I am working on the changes, and it's starting to make more sense. I think I need much more practice tho. It is a little overwhelming.
